In [1]:
import torch
import sklearn
import numpy as np

In [14]:
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory
#import os
#print(os.listdir("../input"))
# Any results you write to the current directory are saved as output.
from pandas import read_csv
#Lets load the dataset and sample some
#column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
#data = read_csv('/home/zamarseny/Data_Science/handson-ml/datasets/housing/housing.csv', header=None, delimiter=r"\s+", names=column_names)
data = read_csv('/home/zamarseny/Data_Science/handson-ml/datasets/housing/housing.csv', \
                #header=None, \
                delimiter=','\
                #, names=column_names\
               )
print(data.head(5))

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  


In [15]:
#data.describe()
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [16]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [49]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
#le.fit(data.ocean_proximity)
#le.classes_
int_prox=le.fit_transform(data.ocean_proximity)
le.transform()

In [50]:
int_prox

array([3, 3, 3, ..., 1, 1, 1])

In [57]:
integer_encoded = int_prox.reshape(len(int_prox), 1)
print(integer_encoded)
print(integer_encoded.shape)

[[3]
 [3]
 [3]
 ...
 [1]
 [1]
 [1]]
(20640, 1)


In [59]:
keys=data.ocean_proximity.unique()
values=le.transform(data.ocean_proximity.unique())
#di=dict(zip(keys,values))
dictlist=[]
for key, value in zip(keys,values):#dict.iteritems():
    temp = [key,value]
    dictlist.append(temp)

In [65]:
dictlist=np.array(dictlist)
print(dictlist)
dictlist.shape

[['NEAR BAY' '3']
 ['<1H OCEAN' '0']
 ['INLAND' '1']
 ['NEAR OCEAN' '4']
 ['ISLAND' '2']]


(5, 2)

In [58]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(\
                    #handle_unknown='ignore'\
                   sparse=False)
#enc.fit(dictlist)
enc.fit_transform(integer_encoded\
                  #, y=None\
                 )

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [66]:
OH_labels=dictlist[:,0]
OH_labels

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype='<U10')